#            _       _ _
#    ___    | | __ _(_) |
#   / _ \_  | |/ _` | | |
#  |  __/ |_| | (_| | | |
#   \___|\___/ \__,_|_|_|
#
# Discord: discord.eplugins.com.br
# Site: eplugins.com.br

# Configuração do banco de dados
database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Diminuir o tempo de jogadores offline
minus-offline: false

# Sistema de Prisão por IP
ip-arrest:
  # Se verdadeiro, quando um jogador for preso, todos os outros jogadores com o mesmo IP também serão presos
  enabled: false
  # Mensagem mostrada para jogadores presos por terem o mesmo IP
  # {reason} - Motivo da prisão original
  ip-arrest-reason: '{reason}'

# Quebrar somente com o item dado pelo plugin?
break-only-plugin: true

# Tag para o jogador preso
# Placeholder: %ejail_arrested_tag%
tag:
  arrested: '&c[PRESO]' # Quando o jogador estiver preso
  free: '&a[LIVRE]' # Quando o jogador estiver livre

# NBT de Itens que não serão guardados, mas sim deletados
nbt-item-delete: ['']
