#       ____  _                       _ _   _             _
#   ___|  _ \(_)___  ___ ___  _ __ __| | | | | ___   ___ | | __
#  / _ \ | | | / __|/ __/ _ \| '__/ _` | |_| |/ _ \ / _ \| |/ /
# |  __/ |_| | \__ \ (_| (_) | | | (_| |  _  | (_) | (_) |   <
#  \___|____/|_|___/\___\___/|_|  \__,_|_| |_|\___/ \___/|_|\_\
#
# Discord: discord.eplugins.com.br
# Site: eplugins.com.br

# Configuração do banco de dados
database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Delay para carregar os dados depois do login
# Recomendado: 20 ticks
login-delay: 20

# Opções gerais do plugin
options:
  # Configurações do bot do Discord
  bot:
    # Token do bot (obrigatório)
    token: ''

    # ID do servidor no Discord (obrigatório)
    guild: ''

    # Atividade do bot
    activity:
      # Intervalo em segundos para atualizar
      # Recomendado no mínimo 5
      interval: 5

      # Textos exibidos na atividade
      # Placeholders:
      # %players% => Quantidade de jogadores online
      # PlaceholderAPI disponível
      frames:
        - 'Jogadores online: %online%'
        - 'Somos o melhor servidor!'
        - 'Vincule sua conta com /vinculardc'

    # Vincular a conta Discord + Minecraft
    account-linking:
      # ID do Canal para enviar as logs de vínculo (o /vinculardc somente vai funcionar nesse canal!)
      channel: ''

    # Envia mensage do Minicraft para o Discord
    messaging-channels:
      # Formatos das mensagens trocadas entre Minecraft e Discord
      formats:
        # Formato das mensgens do Minecraft enviadas ao Discord
        minecraft-messages: '%vault_prefix% {player}'
        # Formato das mensagen do Discord enviadas ao Minecraft
        discord-messages: '&b[Discord] {group} {username}: &f{message}'

      # Enviar mensagens do Minecraft para um canal no discord
      # Para mensagens de chat dos jogadores (quando não se utiliza um plugin de chat): global (Compativel com nChat)
      # Para mensagens de início/parada do servidor: status
      # Para mensagens de conquista/avanço: awards
      # Para mensagens de morte: deaths
      # Para mensagens de entrada: join
      # Para mensagens de saída: leave
      # Formato: 'global:0000000000000000000' (0000000000000000000 = ID DO CANAL NO DISCORD)
      channels:
        - ''

  # Sistema de aviso para vincular
  warnings:
    messages:
      - ''
      - ' &aVocê ainda não vinculou sua conta do discord.'
      - ' &7Utilize &f/vinculardc&7 para vincular.'
      - ''

  # Tag de vinculado
  # %ediscordhook_tag%
  tag: '&a[Vinculado]'

  # Cargo do mito (integração com o plugin eMito)
  # Entregue no Discord ao jogador que estiver com a tag de mito no servidor,
  # somente se ele estiver vinculado. Removido de quem perde a tag.
  mito:
    # ID do cargo no discord
    cargoID: ''

  # Enviar mensagem no chat apenas se estiver vinculado
  chat-linked: false

  # Habilitar o jogador desvincular o discord
  unlink: false

  # Lista de comandos executados no jogador, Após a vinculação
  commands: ['give {player} diamond 1']

  # Sistema de recompensa
  reward:
    # A recompensa somente vai ser entregue na primeira vez?
    first-time: true
    
    # Recompensas entregues ao jogador quando concluir a vinculação
    # chance,recompensa
    rewards:
      - '100,Reco1'