#      _____                           ___        _ _            
#   __|_   _|__ _ __ ___  _ __   ___  / _ \ _ __ | (_)_ __   ___ 
#  / _ \| |/ _ \ '_ ` _ \| '_ \ / _ \| | | | '_ \| | | '_ \ / _ \
# |  __/| |  __/ | | | | | |_) | (_) | |_| | | | | | | | | |  __/
#  \___||_|\___|_| |_| |_| .__/ \___/ \___/|_| |_|_|_|_| |_|\___|
#                        |_|                                      
# Discord: discord.eplugins.com.br
# Site: eplugins.com.br

# Configuração do banco de dados
database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Opções gerais do plugin
options:
  # Tag que será dada ao TOP 1 do tempo online
  tag: '&a[VICIADO]'

  # Limpar as missões coletadas ao resetar pelo /tempo reset
  clear-collected-reset: true

  # Resetar o tempo atual (de recompensas diretas) ao deslogar do servidor
  logout-reset-actual: false

  # Recompensas diretas vai pegar o Tempo Atual?
  current-time-rewards: true